# Markdownlint configuration
# See: https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

# Default rules
default: true

# MD003 - Header style
MD003:
  style: "atx"

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD013 - Line length
MD013:
  line_length: 120
  headings: false
  tables: false
  code_blocks: false

# MD024 - Multiple headers with the same content
MD024:
  allow_different_nesting: true

# MD026 - Trailing punctuation in header
MD026:
  punctuation: ".,;:!?"

# MD029 - Ordered list item prefix
MD029:
  style: "ordered"

# MD033 - Inline HTML
MD033:
  allowed_elements:
    - "br"
    - "details"
    - "summary"
    - "img"
    - "a"
    - "code"
    - "pre"
    - "div"
    - "span"
    - "table"
    - "tr"
    - "td"
    - "th"
    - "thead"
    - "tbody"

# MD034 - Bare URL used
MD034: false

# MD041 - First line in file should be a top level header
MD041: false

# MD046 - Code block style
MD046:
  style: "fenced"