version: '3.8'
services:
  surrogate-optimizer:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - WORKERS=4
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "from surrogate_optim import SurrogateOptimizer; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    
  redis-cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    
volumes:
  redis-data:
